# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38717ab8b92e47e8617d66b2aad089d6f7a5d05817a63bf2f13b4b8e552da0b91d9fdf2e0a4b6ec6f1e0384ae10a98983991c4e65327848ff1695a19153f59bc

test:
  secret_key_base: dcce453c73e6022078818256e066288692374e0120d39480ae1d5f42aea9dc3f5003c00f854d6b9c8116760791fdb7c16ed116433928d60f70bebcfab2944238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
